# fly.toml app configuration file generated for wsa-utopia-discord-bot-ai-agent on 2024-08-19T21:08:12+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wsa-utopia-discord-bot-ai-agent'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0
  ports = []

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
