# fly.toml app configuration file generated for wsa-utopia-discord-bot-ai-agent-cold-surf-3468 on 2024-08-19T19:46:31+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wsa-utopia-discord-bot-ai-agent-cold-surf-3468'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
